package com.itproject.game;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.TextureRegion;
import com.badlogic.gdx.maps.tiled.TiledMap;
import com.badlogic.gdx.maps.tiled.TiledMapRenderer;
import com.badlogic.gdx.maps.tiled.TmxMapLoader;
import com.badlogic.gdx.maps.tiled.renderers.IsometricTiledMapRenderer;
import com.badlogic.gdx.maps.tiled.tiles.AnimatedTiledMapTile;
import com.badlogic.gdx.maps.tiled.tiles.StaticTiledMapTile;
import com.badlogic.gdx.utils.Array;

public class Assets {

	// Down below will be all resources, textures & stuff
	
	public static Texture items;
	
	public static Texture grass;
	public static TextureRegion demoGrass;
	// HOUSE
	public static Texture house;
	public static TextureRegion houseCell1;
	public static TextureRegion houseCell2;
	public static TextureRegion houseCell3;
	public static TextureRegion houseCell4;
	public static Texture houseSelected;
	public static TextureRegion houseSelectedCell1;
	public static TextureRegion houseSelectedCell2;
	public static TextureRegion houseSelectedCell3;
	public static TextureRegion houseSelectedCell4;	
	public static Texture houseGreen;
	public static TextureRegion houseGreenCell1;
	public static TextureRegion houseGreenCell2;
	public static TextureRegion houseGreenCell3;
	public static TextureRegion houseGreenCell4;	
	public static Texture houseRedactor;
	public static TextureRegion houseRedactorRegion;
	// FIRESTATION
	public static Texture fireStation;
	public static TextureRegion fireStationCell1;
	public static TextureRegion fireStationCell2;
	public static TextureRegion fireStationCell3;
	public static TextureRegion fireStationCell4;
	public static Texture fireStationSelected;
	public static TextureRegion selectedFireStationCell1;
	public static TextureRegion selectedFireStationCell2;
	public static TextureRegion selectedFireStationCell3;
	public static TextureRegion selectedFireStationCell4;
	public static Texture fireStationGreen;
	public static TextureRegion fireStationGreenCell1;
	public static TextureRegion fireStationGreenCell2;
	public static TextureRegion fireStationGreenCell3;
	public static TextureRegion fireStationGreenCell4;
	public static Texture fireStationRedactor;
	public static TextureRegion fireStationRedactorRegion;
	// POLICESTATION
	public static Texture policeStation;
	public static TextureRegion policeStationCell1;
	public static TextureRegion policeStationCell2;
	public static TextureRegion policeStationCell3;
	public static TextureRegion policeStationCell4;
	public static Texture policeStationSelected;
	public static TextureRegion policeStationSelectedCell1;
	public static TextureRegion policeStationSelectedCell2;
	public static TextureRegion policeStationSelectedCell3;
	public static TextureRegion policeStationSelectedCell4;
	public static Texture policeStationGreen;
	public static TextureRegion policeStationGreenCell1;
	public static TextureRegion policeStationGreenCell2;
	public static TextureRegion policeStationGreenCell3;
	public static TextureRegion policeStationGreenCell4;
	public static Texture policeStationRedactor;
	public static TextureRegion policeStationRedactorRegion;
	// HOSPITAL
	public static Texture hospital;
	public static TextureRegion hospitalCell1;
	public static TextureRegion hospitalCell2;
	public static TextureRegion hospitalCell3;
	public static TextureRegion hospitalCell4;
	public static TextureRegion hospitalCell5;
	public static TextureRegion hospitalCell6;
	public static Texture hospitalSelected;
	public static TextureRegion hospitalSelectedCell1;
	public static TextureRegion hospitalSelectedCell2;
	public static TextureRegion hospitalSelectedCell3;
	public static TextureRegion hospitalSelectedCell4;
	public static TextureRegion hospitalSelectedCell5;
	public static TextureRegion hospitalSelectedCell6;
	public static Texture hospitalGreen;
	public static TextureRegion hospitalGreenCell1;
	public static TextureRegion hospitalGreenCell2;
	public static TextureRegion hospitalGreenCell3;
	public static TextureRegion hospitalGreenCell4;
	public static TextureRegion hospitalGreenCell5;
	public static TextureRegion hospitalGreenCell6;
	public static Texture hospitalRedactor;
	public static TextureRegion hospitalRedactorRegion;
	// BANK
	public static Texture bank;
	public static TextureRegion bankCell1;
	public static TextureRegion bankCell2;
	public static TextureRegion bankCell3;
	public static TextureRegion bankCell4;
	public static Texture bankSelected;
	public static TextureRegion bankSelectedCell1;
	public static TextureRegion bankSelectedCell2;
	public static TextureRegion bankSelectedCell3;
	public static TextureRegion bankSelectedCell4;
	public static Texture bankGreen;
	public static TextureRegion bankGreenCell1;
	public static TextureRegion bankGreenCell2;
	public static TextureRegion bankGreenCell3;
	public static TextureRegion bankGreenCell4;
	public static Texture bankRedactor;
	public static TextureRegion bankRedactorRegion;
	// GROCERY SHOP
	public static Texture groceryShop;
	public static TextureRegion groceryShopCell1;
	public static TextureRegion groceryShopCell2;
	public static Texture groceryShopSelected;
	public static TextureRegion groceryShopSelectedCell1;
	public static TextureRegion groceryShopSelectedCell2;
	public static Texture groceryShopGreen;
	public static TextureRegion groceryShopGreenCell1;
	public static TextureRegion groceryShopGreenCell2;
	public static Texture groceryShopRedactor;
	public static TextureRegion groceryShopRedactorRegion;
	// BAR
	public static Texture bar;
	public static TextureRegion barCell1;
	public static TextureRegion barCell2;
	public static TextureRegion barCell3;
	public static TextureRegion barCell4;
	public static Texture barSelected;
	public static TextureRegion barSelectedCell1;
	public static TextureRegion barSelectedCell2;
	public static TextureRegion barSelectedCell3;
	public static TextureRegion barSelectedCell4;
	public static Texture barGreen;
	public static TextureRegion barGreenCell1;
	public static TextureRegion barGreenCell2;
	public static TextureRegion barGreenCell3;
	public static TextureRegion barGreenCell4;
	public static Texture barRedactor;
	public static TextureRegion barRedactorRegion;
	// POWER STATION
	public static Texture powerStation;
	public static TextureRegion powerStationCell1;
	public static TextureRegion powerStationCell2;
	public static TextureRegion powerStationCell3;
	public static TextureRegion powerStationCell4;
	public static TextureRegion powerStationCell5;
	public static TextureRegion powerStationCell6;
	public static TextureRegion powerStationCell7;
	public static TextureRegion powerStationCell8;
	public static TextureRegion powerStationCell9;
	public static Texture powerStationSelected;
	public static TextureRegion powerStationSelectedCell1;
	public static TextureRegion powerStationSelectedCell2;
	public static TextureRegion powerStationSelectedCell3;
	public static TextureRegion powerStationSelectedCell4;
	public static TextureRegion powerStationSelectedCell5;
	public static TextureRegion powerStationSelectedCell6;
	public static TextureRegion powerStationSelectedCell7;
	public static TextureRegion powerStationSelectedCell8;
	public static TextureRegion powerStationSelectedCell9;
	public static Texture powerStationGreen;
	public static TextureRegion powerStationGreenCell1;
	public static TextureRegion powerStationGreenCell2;
	public static TextureRegion powerStationGreenCell3;
	public static TextureRegion powerStationGreenCell4;
	public static TextureRegion powerStationGreenCell5;
	public static TextureRegion powerStationGreenCell6;
	public static TextureRegion powerStationGreenCell7;
	public static TextureRegion powerStationGreenCell8;
	public static TextureRegion powerStationGreenCell9;
	public static Texture powerStationRedactor;
	public static TextureRegion powerStationRedactorRegion;
	// OIL PLANT
	public static Texture oilPlant;
	public static TextureRegion oilPlantCell1;
	public static TextureRegion oilPlantCell2;
	public static TextureRegion oilPlantCell3;
	public static TextureRegion oilPlantCell4;
	public static TextureRegion oilPlantCell5;
	public static TextureRegion oilPlantCell6;
	public static TextureRegion oilPlantCell7;
	public static TextureRegion oilPlantCell8;
	public static TextureRegion oilPlantCell9;
	public static Texture oilPlantSelected;
	public static TextureRegion oilPlantSelectedCell1;
	public static TextureRegion oilPlantSelectedCell2;
	public static TextureRegion oilPlantSelectedCell3;
	public static TextureRegion oilPlantSelectedCell4;
	public static TextureRegion oilPlantSelectedCell5;
	public static TextureRegion oilPlantSelectedCell6;
	public static TextureRegion oilPlantSelectedCell7;
	public static TextureRegion oilPlantSelectedCell8;
	public static TextureRegion oilPlantSelectedCell9;
	public static Texture oilPlantGreen;
	public static TextureRegion oilPlantGreenCell1;
	public static TextureRegion oilPlantGreenCell2;
	public static TextureRegion oilPlantGreenCell3;
	public static TextureRegion oilPlantGreenCell4;
	public static TextureRegion oilPlantGreenCell5;
	public static TextureRegion oilPlantGreenCell6;
	public static TextureRegion oilPlantGreenCell7;
	public static TextureRegion oilPlantGreenCell8;
	public static TextureRegion oilPlantGreenCell9;
	public static Texture oilPlantRedactor;
	public static TextureRegion oilPlantRedactorRegion;
	// IRON PLANT
	public static Texture ironPlant;
	public static TextureRegion ironPlantCell1;
	public static TextureRegion ironPlantCell2;
	public static TextureRegion ironPlantCell3;
	public static TextureRegion ironPlantCell4;
	public static TextureRegion ironPlantCell5;
	public static TextureRegion ironPlantCell6;
	public static TextureRegion ironPlantCell7;
	public static TextureRegion ironPlantCell8;
	public static TextureRegion ironPlantCell9;
	public static Texture ironPlantSelected;
	public static TextureRegion ironPlantSelectedCell1;
	public static TextureRegion ironPlantSelectedCell2;
	public static TextureRegion ironPlantSelectedCell3;
	public static TextureRegion ironPlantSelectedCell4;
	public static TextureRegion ironPlantSelectedCell5;
	public static TextureRegion ironPlantSelectedCell6;
	public static TextureRegion ironPlantSelectedCell7;
	public static TextureRegion ironPlantSelectedCell8;
	public static TextureRegion ironPlantSelectedCell9;
	public static Texture ironPlantGreen;
	public static TextureRegion ironPlantGreenCell1;
	public static TextureRegion ironPlantGreenCell2;
	public static TextureRegion ironPlantGreenCell3;
	public static TextureRegion ironPlantGreenCell4;
	public static TextureRegion ironPlantGreenCell5;
	public static TextureRegion ironPlantGreenCell6;
	public static TextureRegion ironPlantGreenCell7;
	public static TextureRegion ironPlantGreenCell8;
	public static TextureRegion ironPlantGreenCell9;
	public static Texture ironPlantRedactor;
	public static TextureRegion ironPlantRedactorRegion;
	// PARK
	public static Texture park;
	public static TextureRegion parkCell1;
	public static TextureRegion parkCell2;
	public static TextureRegion parkCell3;
	public static TextureRegion parkCell4;
	public static TextureRegion parkCell5;
	public static TextureRegion parkCell6;
	public static TextureRegion parkCell7;
	public static TextureRegion parkCell8;
	public static TextureRegion parkCell9;
	public static Texture parkSelected;
	public static TextureRegion parkSelectedCell1;
	public static TextureRegion parkSelectedCell2;
	public static TextureRegion parkSelectedCell3;
	public static TextureRegion parkSelectedCell4;
	public static TextureRegion parkSelectedCell5;
	public static TextureRegion parkSelectedCell6;
	public static TextureRegion parkSelectedCell7;
	public static TextureRegion parkSelectedCell8;
	public static TextureRegion parkSelectedCell9;
	public static Texture parkGreen;
	public static TextureRegion parkGreenCell1;
	public static TextureRegion parkGreenCell2;
	public static TextureRegion parkGreenCell3;
	public static TextureRegion parkGreenCell4;
	public static TextureRegion parkGreenCell5;
	public static TextureRegion parkGreenCell6;
	public static TextureRegion parkGreenCell7;
	public static TextureRegion parkGreenCell8;
	public static TextureRegion parkGreenCell9;
	public static Texture parkRedactor;
	public static TextureRegion parkRedactorRegion;
	// WTC
	public static Texture wtc;
	public static TextureRegion wtcCell1;
	public static TextureRegion wtcCell2;
	public static TextureRegion wtcCell3;
	public static TextureRegion wtcCell4;
	public static Texture wtcSelected;
	public static TextureRegion wtcSelectedCell1;
	public static TextureRegion wtcSelectedCell2;
	public static TextureRegion wtcSelectedCell3;
	public static TextureRegion wtcSelectedCell4;
	public static Texture wtcGreen;
	public static TextureRegion wtcGreenCell1;
	public static TextureRegion wtcGreenCell2;
	public static TextureRegion wtcGreenCell3;
	public static TextureRegion wtcGreenCell4;
	public static Texture wtcRedactor;
	public static TextureRegion wtcRedactorRegion;
	// WATER STATION
	public static Texture waterStation;
	public static TextureRegion waterStationRegion;
	public static Texture waterStationSelected;
	public static TextureRegion waterStationSelectedCell;
	public static Texture waterStationGreen;
	public static TextureRegion waterStationGreenCell;
	// CITYHALL
	public static Texture cityHall;
	public static TextureRegion cityHallCell1;
	public static TextureRegion cityHallCell2;
	public static TextureRegion cityHallCell3;
	public static TextureRegion cityHallCell4;
	public static TextureRegion cityHallCell5;
	public static TextureRegion cityHallCell6;
	public static Texture cityHallSelected;
	public static TextureRegion cityHallSelectedCell1;
	public static TextureRegion cityHallSelectedCell2;
	public static TextureRegion cityHallSelectedCell3;
	public static TextureRegion cityHallSelectedCell4;
	public static TextureRegion cityHallSelectedCell5;
	public static TextureRegion cityHallSelectedCell6;
	public static Texture cityHallGreen;
	public static TextureRegion cityHallGreenCell1;
	public static TextureRegion cityHallGreenCell2;
	public static TextureRegion cityHallGreenCell3;
	public static TextureRegion cityHallGreenCell4;
	public static TextureRegion cityHallGreenCell5;
	public static TextureRegion cityHallGreenCell6;
	public static Texture cityHallRedactor;
	public static TextureRegion cityHallRedactorRegion;
	

	public static Texture redactorMenu;
	public static TextureRegion demoRedactorMenu;
	
	public static TiledMap tiledMap;
	public static TiledMapRenderer tiledMapRenderer;
	
	public static Texture waterDrop;
	public static TextureRegion waterDropRegion;
	public static Texture electricity;
	public static TextureRegion electricityRegion;
	
	
	public static TextureRegion mainMenuPlayButton;

	public static Texture loadTexture(String file) {
		return new Texture(Gdx.files.internal(file));
	}

	static StaticTiledMapTile[] fireStationTiles;
	static StaticTiledMapTile[] bankGreenTiles;
	static StaticTiledMapTile[] groceryShopGreenTiles;
	static StaticTiledMapTile[] barGreenTiles;
	static StaticTiledMapTile[] powerStationGreenTiles;
	static StaticTiledMapTile[] oilPlantGreenTiles;
	static StaticTiledMapTile[] ironPlantGreenTiles;
	static StaticTiledMapTile[] hospitalGreenTiles;
	static StaticTiledMapTile[] parkGreenTiles;
	static StaticTiledMapTile[] wtcGreenTiles;
	static StaticTiledMapTile[] waterStationGreenTiles;
	static StaticTiledMapTile[] policeStationGreenTiles;
	static StaticTiledMapTile[] houseGreenTiles;
	static StaticTiledMapTile[] cityHallGreenTiles;
	
	static Array<StaticTiledMapTile> waterDropAnimation;
	public static AnimatedTiledMapTile waterDropTile;
	static StaticTiledMapTile waterCell1;
	static StaticTiledMapTile waterCell2;
	static StaticTiledMapTile waterCell3;
	static StaticTiledMapTile waterCell4;
	static StaticTiledMapTile waterCell5;
	static StaticTiledMapTile waterCell6;
	static StaticTiledMapTile waterCell7;
	static StaticTiledMapTile waterCell8;
	static StaticTiledMapTile waterCell9;
	
	public static void load() {
		
		waterDropAnimation = new Array<>();
		waterCell1 = new StaticTiledMapTile(new TextureRegion(new Texture("data/waterDropAnimated.png"), 0, 0, 64, 32));
		waterCell2 = new StaticTiledMapTile(new TextureRegion(new Texture("data/waterDropAnimated.png"), 64, 0, 64, 32));
		waterCell3 = new StaticTiledMapTile(new TextureRegion(new Texture("data/waterDropAnimated.png"), 128, 0, 64, 32));
		waterCell4 = new StaticTiledMapTile(new TextureRegion(new Texture("data/waterDropAnimated.png"), 0, 32, 64, 32));
		waterCell5 = new StaticTiledMapTile(new TextureRegion(new Texture("data/waterDropAnimated.png"), 64, 32, 64, 32));
		waterCell6 = new StaticTiledMapTile(new TextureRegion(new Texture("data/waterDropAnimated.png"), 128, 32, 64, 32));
		waterCell7 = new StaticTiledMapTile(new TextureRegion(new Texture("data/waterDropAnimated.png"), 0, 64, 64, 32));
		waterCell8 = new StaticTiledMapTile(new TextureRegion(new Texture("data/waterDropAnimated.png"), 64, 64, 64, 32));
		waterCell9 = new StaticTiledMapTile(new TextureRegion(new Texture("data/waterDropAnimated.png"), 128, 64, 64, 32));
		waterDropAnimation.addAll(waterCell1, waterCell2, waterCell3, waterCell4, waterCell5, waterCell6, waterCell7, waterCell8, waterCell9,
		waterCell9, waterCell8, waterCell7, waterCell6, waterCell5, waterCell4,waterCell3, waterCell2, waterCell1);
		waterDropTile = new AnimatedTiledMapTile(100f, waterDropAnimation);
		
		
		// For now just a few examples
		mainMenuPlayButton = new TextureRegion(new Texture("data/mainMenuPlayButton_demo.png"));

		tiledMap = new TmxMapLoader().load("data/test_map.tmx");
		tiledMapRenderer = new IsometricTiledMapRenderer(Assets.tiledMap);
	
		grass = loadTexture("data/grass_demo1.png");
		demoGrass = new TextureRegion(grass);
		
		redactorMenu = loadTexture("data/redactorMenu_demo.png");
		demoRedactorMenu = new TextureRegion(redactorMenu);
		
		// House Textures Initialization
		house = loadTexture("data/house.png");
		houseCell1 = new TextureRegion(house, 0, 0, 64, 96);
		houseCell2 = new TextureRegion(house,64, 0, 64, 96);
		houseCell3 = new TextureRegion(house,0, 96, 64, 96);
		houseCell4 = new TextureRegion(house,64, 96, 64, 96);
		houseSelected = loadTexture("data/houseSelected.png");
		houseSelectedCell1 = new TextureRegion(houseSelected, 0, 0, 64, 96);
		houseSelectedCell2 = new TextureRegion(houseSelected,64, 0, 64, 96);
		houseSelectedCell3 = new TextureRegion(houseSelected,0, 96, 64, 96);
		houseSelectedCell4 = new TextureRegion(houseSelected,64, 96, 64, 96);
		houseGreen = loadTexture("data/houseGreen.png");
		houseGreenCell1 = new TextureRegion(houseGreen, 0, 0, 64, 96);
		houseGreenCell2 = new TextureRegion(houseGreen,64, 0, 64, 96);
		houseGreenCell3 = new TextureRegion(houseGreen,0, 96, 64, 96);
		houseGreenCell4 = new TextureRegion(houseGreen,64, 96, 64, 96);
		houseGreenTiles = new StaticTiledMapTile[4];
		houseGreenTiles[0] = new StaticTiledMapTile(Assets.houseGreenCell3);
		houseGreenTiles[1] = new StaticTiledMapTile(Assets.houseGreenCell4);
		houseGreenTiles[2] = new StaticTiledMapTile(Assets.houseGreenCell1);
		houseGreenTiles[3] = new StaticTiledMapTile(Assets.houseGreenCell2);
		houseRedactor = loadTexture("data/houseRedactor.png");
		houseRedactorRegion = new TextureRegion(houseRedactor);
		// City Hall Textures Initialization
		cityHallRedactor = loadTexture("data/cityHallRedactor.png");
		cityHallRedactorRegion = new TextureRegion(cityHallRedactor);
		cityHall = loadTexture("data/cityHall.png");
		cityHallCell1 = new TextureRegion(cityHall, 0, 0, 64, 96);
		cityHallCell2 = new TextureRegion(cityHall, 64, 0, 64, 96);
		cityHallCell3 = new TextureRegion(cityHall, 0, 96, 64, 96);
		cityHallCell4 = new TextureRegion(cityHall, 64, 96, 64, 96);
		cityHallCell5 = new TextureRegion(cityHall, 0, 192, 64, 96);
		cityHallCell6 = new TextureRegion(cityHall, 64, 192, 64, 96);
		cityHallSelected = loadTexture("data/cityHallSelected.png");
		cityHallSelectedCell1 = new TextureRegion(cityHallSelected, 0, 0, 64, 96);
		cityHallSelectedCell2 = new TextureRegion(cityHallSelected, 64, 0, 64, 96);
		cityHallSelectedCell3 = new TextureRegion(cityHallSelected, 0, 96, 64, 96);
		cityHallSelectedCell4 = new TextureRegion(cityHallSelected, 64, 96, 64, 96);
		cityHallSelectedCell5 = new TextureRegion(cityHallSelected, 0, 192, 64, 96);
		cityHallSelectedCell6 = new TextureRegion(cityHallSelected, 64, 192, 64, 96);
		cityHallGreen = loadTexture("data/cityHallGreen.png");
		cityHallGreenCell1 = new TextureRegion(cityHallGreen, 0, 0, 64, 96);
		cityHallGreenCell2 = new TextureRegion(cityHallGreen, 64, 0, 64, 96);
		cityHallGreenCell3 = new TextureRegion(cityHallGreen, 0, 96, 64, 96);
		cityHallGreenCell4 = new TextureRegion(cityHallGreen, 64, 96, 64, 96);
		cityHallGreenCell5 = new TextureRegion(cityHallGreen, 0, 192, 64, 96);
		cityHallGreenCell6 = new TextureRegion(cityHallGreen, 64, 192, 64, 96);
		cityHallGreenTiles = new StaticTiledMapTile[6];
		cityHallGreenTiles[0] = new StaticTiledMapTile(Assets.cityHallGreenCell5);
		cityHallGreenTiles[1] = new StaticTiledMapTile(Assets.cityHallGreenCell6);
		cityHallGreenTiles[2] = new StaticTiledMapTile(Assets.cityHallGreenCell3);
		cityHallGreenTiles[3] = new StaticTiledMapTile(Assets.cityHallGreenCell4);
		cityHallGreenTiles[4] = new StaticTiledMapTile(Assets.cityHallGreenCell1);
		cityHallGreenTiles[5] = new StaticTiledMapTile(Assets.cityHallGreenCell2);
		// Bank Textures initialization
		bank = loadTexture("data/bank.png");
		bankCell1 = new TextureRegion(bank,0 ,0, 64, 96);
		bankCell2 = new TextureRegion(bank,64, 0, 64, 96);
		bankCell3 = new TextureRegion(bank,0, 96, 64, 96);
		bankCell4 = new TextureRegion(bank,64, 96, 64, 96);
		bankSelected = loadTexture("data/bankSelected.png");
		bankSelectedCell1 = new TextureRegion(bankSelected,0 ,0, 64, 96);
		bankSelectedCell2 = new TextureRegion(bankSelected,64, 0, 64, 96);
		bankSelectedCell3 = new TextureRegion(bankSelected,0, 96, 64, 96);
		bankSelectedCell4 = new TextureRegion(bankSelected,64, 96, 64, 96);
		bankGreen = loadTexture("data/bankGreen.png");
		bankGreenCell1 = new TextureRegion(bankGreen,0 ,0, 64, 96);
		bankGreenCell2 = new TextureRegion(bankGreen,64, 0, 64, 96);
		bankGreenCell3 = new TextureRegion(bankGreen,0, 96, 64, 96);
		bankGreenCell4 = new TextureRegion(bankGreen,64, 96, 64, 96);
		bankGreenTiles = new StaticTiledMapTile[4];
		bankGreenTiles[0] = new StaticTiledMapTile(Assets.bankGreenCell3);
		bankGreenTiles[1] = new StaticTiledMapTile(Assets.bankGreenCell4);
		bankGreenTiles[2] = new StaticTiledMapTile(Assets.bankGreenCell1);
		bankGreenTiles[3] = new StaticTiledMapTile(Assets.bankGreenCell2);
		bankRedactor = loadTexture("data/bank_redactor.png");
		bankRedactorRegion = new TextureRegion(bankRedactor);
		// Bar Texture initialization
		bar = loadTexture("data/bar.png");
		barCell1 = new TextureRegion(bar,0 ,0, 64, 96);
		barCell2 = new TextureRegion(bar,64, 0, 64, 96);
		barCell3 = new TextureRegion(bar,0, 96, 64, 96);
		barCell4 = new TextureRegion(bar,64, 96, 64, 96);
		barSelected = loadTexture("data/barSelected.png");
		barSelectedCell1 = new TextureRegion(barSelected,0 ,0, 64, 96);
		barSelectedCell2 = new TextureRegion(barSelected,64, 0, 64, 96);
		barSelectedCell3 = new TextureRegion(barSelected,0, 96, 64, 96);
		barSelectedCell4 = new TextureRegion(barSelected,64, 96, 64, 96);
		barGreen = loadTexture("data/barGreen.png");
		barGreenCell1 = new TextureRegion(barGreen,0 ,0, 64, 96);
		barGreenCell2 = new TextureRegion(barGreen,64, 0, 64, 96);
		barGreenCell3 = new TextureRegion(barGreen,0, 96, 64, 96);
		barGreenCell4 = new TextureRegion(barGreen,64, 96, 64, 96);
		barGreenTiles = new StaticTiledMapTile[4];
		barGreenTiles[0] = new StaticTiledMapTile(Assets.barGreenCell3);
		barGreenTiles[1] = new StaticTiledMapTile(Assets.barGreenCell4);
		barGreenTiles[2] = new StaticTiledMapTile(Assets.barGreenCell1);
		barGreenTiles[3] = new StaticTiledMapTile(Assets.barGreenCell2);
		barRedactor = loadTexture("data/barRedactor.png");
		barRedactorRegion = new TextureRegion(barRedactor);
		// Grocery shop Textures initialization
		groceryShop = loadTexture("data/groceryShop.png");
		groceryShopCell2 = new TextureRegion(groceryShop,0 ,0, 64, 96);
		groceryShopCell1 = new TextureRegion(groceryShop,0, 96	, 64, 96);
		groceryShopSelected = loadTexture("data/groceryShopSelected.png");
		groceryShopSelectedCell2 = new TextureRegion(groceryShopSelected,0 ,0, 64, 96);
		groceryShopSelectedCell1 = new TextureRegion(groceryShopSelected,0, 96, 64, 96);
		groceryShopGreen = loadTexture("data/groceryShopGreen.png");
		groceryShopGreenCell2 = new TextureRegion(groceryShopGreen,0 ,0, 64, 96);
		groceryShopGreenCell1 = new TextureRegion(groceryShopGreen,0, 96, 64, 96);
		groceryShopGreenTiles = new StaticTiledMapTile[2];
		groceryShopGreenTiles[0] = new StaticTiledMapTile(Assets.groceryShopGreenCell1);
		groceryShopGreenTiles[1] = new StaticTiledMapTile(Assets.groceryShopGreenCell2);
		groceryShopRedactor = loadTexture("data/groceryShopRedactor.png");
		groceryShopRedactorRegion = new TextureRegion(groceryShopRedactor);
		// power station initialization
		powerStation = loadTexture("data/powerStation.png");
		powerStationCell1 = new TextureRegion(powerStation, 0, 0, 64, 96);
		powerStationCell2 = new TextureRegion(powerStation, 64, 0, 64, 96);
		powerStationCell3 = new TextureRegion(powerStation, 128, 0, 64, 96);
		powerStationCell4 = new TextureRegion(powerStation, 0, 96, 64, 96);
		powerStationCell5 = new TextureRegion(powerStation, 64, 96, 64, 96);
		powerStationCell6 = new TextureRegion(powerStation, 128, 96, 64, 96);
		powerStationCell7 = new TextureRegion(powerStation, 0, 192, 64, 96);
		powerStationCell8 = new TextureRegion(powerStation, 64, 192, 64, 96);
		powerStationCell9 = new TextureRegion(powerStation, 128, 192, 64, 96);
		powerStationSelected = loadTexture("data/powerStationSelected.png");
		powerStationSelectedCell1 = new TextureRegion(powerStationSelected, 0, 0, 64, 96);
		powerStationSelectedCell2 = new TextureRegion(powerStationSelected, 64, 0, 64, 96);
		powerStationSelectedCell3 = new TextureRegion(powerStationSelected, 128, 0, 64, 96);
		powerStationSelectedCell4 = new TextureRegion(powerStationSelected, 0, 96, 64, 96);
		powerStationSelectedCell5 = new TextureRegion(powerStationSelected, 64, 96, 64, 96);
		powerStationSelectedCell6 = new TextureRegion(powerStationSelected, 128, 96, 64, 96);
		powerStationSelectedCell7 = new TextureRegion(powerStationSelected, 0, 192, 64, 96);
		powerStationSelectedCell8 = new TextureRegion(powerStationSelected, 64, 192, 64, 96);
		powerStationSelectedCell9 = new TextureRegion(powerStationSelected, 128, 192, 64, 96);
		powerStationGreen = loadTexture("data/powerStationGreen.png");
		powerStationGreenCell1 = new TextureRegion(powerStationGreen, 0, 0, 64, 96);
		powerStationGreenCell2 = new TextureRegion(powerStationGreen, 64, 0, 64, 96);
		powerStationGreenCell3 = new TextureRegion(powerStationGreen, 128, 0, 64, 96);
		powerStationGreenCell4 = new TextureRegion(powerStationGreen, 0, 96, 64, 96);
		powerStationGreenCell5 = new TextureRegion(powerStationGreen, 64, 96, 64, 96);
		powerStationGreenCell6 = new TextureRegion(powerStationGreen, 128, 96, 64, 96);
		powerStationGreenCell7 = new TextureRegion(powerStationGreen, 0, 192, 64, 96);
		powerStationGreenCell8 = new TextureRegion(powerStationGreen, 64, 192, 64, 96);
		powerStationGreenCell9 = new TextureRegion(powerStationGreen, 128, 192, 64, 96);
		powerStationRedactor = loadTexture("data/powerStationRedactor.png");
		powerStationRedactorRegion = new TextureRegion(powerStationRedactor);
		powerStationGreenTiles = new StaticTiledMapTile[9];
		powerStationGreenTiles[0] = new StaticTiledMapTile(Assets.powerStationGreenCell7);
		powerStationGreenTiles[1] = new StaticTiledMapTile(Assets.powerStationGreenCell8);
		powerStationGreenTiles[2] = new StaticTiledMapTile(Assets.powerStationGreenCell9);
		powerStationGreenTiles[3] = new StaticTiledMapTile(Assets.powerStationGreenCell4);
		powerStationGreenTiles[4] = new StaticTiledMapTile(Assets.powerStationGreenCell5);
		powerStationGreenTiles[5] = new StaticTiledMapTile(Assets.powerStationGreenCell6);
		powerStationGreenTiles[6] = new StaticTiledMapTile(Assets.powerStationGreenCell1);
		powerStationGreenTiles[7] = new StaticTiledMapTile(Assets.powerStationGreenCell2);
		powerStationGreenTiles[8] = new StaticTiledMapTile(Assets.powerStationGreenCell3);
		// oil plant
		oilPlant = loadTexture("data/oilPlant.png");
		oilPlantCell1 = new TextureRegion(oilPlant, 0, 0, 64, 96);
		oilPlantCell2 = new TextureRegion(oilPlant, 64, 0, 64, 96);
		oilPlantCell3 = new TextureRegion(oilPlant, 128, 0, 64, 96);
		oilPlantCell4 = new TextureRegion(oilPlant, 0, 96, 64, 96);
		oilPlantCell5 = new TextureRegion(oilPlant, 64, 96, 64, 96);
		oilPlantCell6 = new TextureRegion(oilPlant, 128, 96, 64, 96);
		oilPlantCell7 = new TextureRegion(oilPlant, 0, 192, 64, 96);
		oilPlantCell8 = new TextureRegion(oilPlant, 64, 192, 64, 96);
		oilPlantCell9 = new TextureRegion(oilPlant, 128, 192, 64, 96);
		oilPlantSelected = loadTexture("data/oilPlantSelected.png");
		oilPlantSelectedCell1 = new TextureRegion(oilPlantSelected, 0, 0, 64, 96);
		oilPlantSelectedCell2 = new TextureRegion(oilPlantSelected, 64, 0, 64, 96);
		oilPlantSelectedCell3 = new TextureRegion(oilPlantSelected, 128, 0, 64, 96);
		oilPlantSelectedCell4 = new TextureRegion(oilPlantSelected, 0, 96, 64, 96);
		oilPlantSelectedCell5 = new TextureRegion(oilPlantSelected, 64, 96, 64, 96);
		oilPlantSelectedCell6 = new TextureRegion(oilPlantSelected, 128, 96, 64, 96);
		oilPlantSelectedCell7 = new TextureRegion(oilPlantSelected, 0, 192, 64, 96);
		oilPlantSelectedCell8 = new TextureRegion(oilPlantSelected, 64, 192, 64, 96);
		oilPlantSelectedCell9 = new TextureRegion(oilPlantSelected, 128, 192, 64, 96);
		oilPlantGreen = loadTexture("data/oilPlantGreen.png");
		oilPlantGreenCell1 = new TextureRegion(oilPlantGreen, 0, 0, 64, 96);
		oilPlantGreenCell2 = new TextureRegion(oilPlantGreen, 64, 0, 64, 96);
		oilPlantGreenCell3 = new TextureRegion(oilPlantGreen, 128, 0, 64, 96);
		oilPlantGreenCell4 = new TextureRegion(oilPlantGreen, 0, 96, 64, 96);
		oilPlantGreenCell5 = new TextureRegion(oilPlantGreen, 64, 96, 64, 96);
		oilPlantGreenCell6 = new TextureRegion(oilPlantGreen, 128, 96, 64, 96);
		oilPlantGreenCell7 = new TextureRegion(oilPlantGreen, 0, 192, 64, 96);
		oilPlantGreenCell8 = new TextureRegion(oilPlantGreen, 64, 192, 64, 96);
		oilPlantGreenCell9 = new TextureRegion(oilPlantGreen, 128, 192, 64, 96);
		oilPlantRedactor = loadTexture("data/oilPlantRedactor.png");
		oilPlantRedactorRegion = new TextureRegion(oilPlantRedactor);
		oilPlantGreenTiles = new StaticTiledMapTile[9];
		oilPlantGreenTiles[0] = new StaticTiledMapTile(Assets.oilPlantGreenCell7);
		oilPlantGreenTiles[1] = new StaticTiledMapTile(Assets.oilPlantGreenCell8);
		oilPlantGreenTiles[2] = new StaticTiledMapTile(Assets.oilPlantGreenCell9);
		oilPlantGreenTiles[3] = new StaticTiledMapTile(Assets.oilPlantGreenCell4);
		oilPlantGreenTiles[4] = new StaticTiledMapTile(Assets.oilPlantGreenCell5);
		oilPlantGreenTiles[5] = new StaticTiledMapTile(Assets.oilPlantGreenCell6);
		oilPlantGreenTiles[6] = new StaticTiledMapTile(Assets.oilPlantGreenCell1);
		oilPlantGreenTiles[7] = new StaticTiledMapTile(Assets.oilPlantGreenCell2);
		oilPlantGreenTiles[8] = new StaticTiledMapTile(Assets.oilPlantGreenCell3);
		// iron plant
		ironPlant = loadTexture("data/ironPlant.png");
		ironPlantCell1 = new TextureRegion(ironPlant, 0, 0, 64, 96);
		ironPlantCell2 = new TextureRegion(ironPlant, 64, 0, 64, 96);
		ironPlantCell3 = new TextureRegion(ironPlant, 128, 0, 64, 96);
		ironPlantCell4 = new TextureRegion(ironPlant, 0, 96, 64, 96);
		ironPlantCell5 = new TextureRegion(ironPlant, 64, 96, 64, 96);
		ironPlantCell6 = new TextureRegion(ironPlant, 128, 96, 64, 96);
		ironPlantCell7 = new TextureRegion(ironPlant, 0, 192, 64, 96);
		ironPlantCell8 = new TextureRegion(ironPlant, 64, 192, 64, 96);
		ironPlantCell9 = new TextureRegion(ironPlant, 128, 192, 64, 96);
		ironPlantSelected = loadTexture("data/ironPlantSelected.png");
		ironPlantSelectedCell1 = new TextureRegion(ironPlantSelected, 0, 0, 64, 96);
		ironPlantSelectedCell2 = new TextureRegion(ironPlantSelected, 64, 0, 64, 96);
		ironPlantSelectedCell3 = new TextureRegion(ironPlantSelected, 128, 0, 64, 96);
		ironPlantSelectedCell4 = new TextureRegion(ironPlantSelected, 0, 96, 64, 96);
		ironPlantSelectedCell5 = new TextureRegion(ironPlantSelected, 64, 96, 64, 96);
		ironPlantSelectedCell6 = new TextureRegion(ironPlantSelected, 128, 96, 64, 96);
		ironPlantSelectedCell7 = new TextureRegion(ironPlantSelected, 0, 192, 64, 96);
		ironPlantSelectedCell8 = new TextureRegion(ironPlantSelected, 64, 192, 64, 96);
		ironPlantSelectedCell9 = new TextureRegion(ironPlantSelected, 128, 192, 64, 96);
		ironPlantGreen = loadTexture("data/ironPlantGreen.png");
		ironPlantGreenCell1 = new TextureRegion(ironPlantGreen, 0, 0, 64, 96);
		ironPlantGreenCell2 = new TextureRegion(ironPlantGreen, 64, 0, 64, 96);
		ironPlantGreenCell3 = new TextureRegion(ironPlantGreen, 128, 0, 64, 96);
		ironPlantGreenCell4 = new TextureRegion(ironPlantGreen, 0, 96, 64, 96);
		ironPlantGreenCell5 = new TextureRegion(ironPlantGreen, 64, 96, 64, 96);
		ironPlantGreenCell6 = new TextureRegion(ironPlantGreen, 128, 96, 64, 96);
		ironPlantGreenCell7 = new TextureRegion(ironPlantGreen, 0, 192, 64, 96);
		ironPlantGreenCell8 = new TextureRegion(ironPlantGreen, 64, 192, 64, 96);
		ironPlantGreenCell9 = new TextureRegion(ironPlantGreen, 128, 192, 64, 96);
		ironPlantRedactor = loadTexture("data/ironPlantRedactor.png");
		ironPlantRedactorRegion = new TextureRegion(ironPlantRedactor);
		ironPlantGreenTiles = new StaticTiledMapTile[9];
		ironPlantGreenTiles[0] = new StaticTiledMapTile(Assets.ironPlantGreenCell7);
		ironPlantGreenTiles[1] = new StaticTiledMapTile(Assets.ironPlantGreenCell8);
		ironPlantGreenTiles[2] = new StaticTiledMapTile(Assets.ironPlantGreenCell9);
		ironPlantGreenTiles[3] = new StaticTiledMapTile(Assets.ironPlantGreenCell4);
		ironPlantGreenTiles[4] = new StaticTiledMapTile(Assets.ironPlantGreenCell5);
		ironPlantGreenTiles[5] = new StaticTiledMapTile(Assets.ironPlantGreenCell6);
		ironPlantGreenTiles[6] = new StaticTiledMapTile(Assets.ironPlantGreenCell1);
		ironPlantGreenTiles[7] = new StaticTiledMapTile(Assets.ironPlantGreenCell2);
		ironPlantGreenTiles[8] = new StaticTiledMapTile(Assets.ironPlantGreenCell3);
		// Water station Textures initialization
		waterStation = loadTexture("data/waterStation.png");
		waterStationRegion = new TextureRegion(waterStation);
		waterStationSelectedCell = new TextureRegion(loadTexture("data/waterStationSelected.png"));
		waterStationGreenCell = new TextureRegion(loadTexture("data/waterStationGreen.png"));
		waterStationGreenTiles = new StaticTiledMapTile[1];
		waterStationGreenTiles[0] = new StaticTiledMapTile(Assets.waterStationGreenCell);
		// Police Station Texture Initialization
		policeStationRedactor = loadTexture("data/policeStationRedactor.png");
		policeStationRedactorRegion = new TextureRegion(policeStationRedactor);
		policeStation = loadTexture("data/policeStation.png");
		policeStationCell1 = new TextureRegion(policeStation, 0, 0, 64, 96);
		policeStationCell2 = new TextureRegion(policeStation, 64, 0, 64, 96);
		policeStationCell3 = new TextureRegion(policeStation, 0, 96, 64, 96);
		policeStationCell4 = new TextureRegion(policeStation, 64, 96, 64, 96);
		policeStationSelected = loadTexture("data/policeStationSelected.png");
		policeStationSelectedCell1 = new TextureRegion(policeStationSelected, 0, 0, 64, 96);
		policeStationSelectedCell2 = new TextureRegion(policeStationSelected, 64, 0, 64, 96);
		policeStationSelectedCell3 = new TextureRegion(policeStationSelected, 0, 96, 64, 96);
		policeStationSelectedCell4 = new TextureRegion(policeStationSelected, 64, 96, 64, 96);
		policeStationGreen = loadTexture("data/policeStationGreen.png");
		policeStationGreenCell1 = new TextureRegion(policeStationGreen, 0, 0, 64, 96);
		policeStationGreenCell2 = new TextureRegion(policeStationGreen, 64, 0, 64, 96);
		policeStationGreenCell3 = new TextureRegion(policeStationGreen, 0, 96, 64, 96);
		policeStationGreenCell4 = new TextureRegion(policeStationGreen, 64, 96, 64, 96);
		policeStationGreenTiles = new StaticTiledMapTile[4];
		policeStationGreenTiles[0] = new StaticTiledMapTile(policeStationGreenCell3);
		policeStationGreenTiles[1] = new StaticTiledMapTile(policeStationGreenCell4);
		policeStationGreenTiles[2] = new StaticTiledMapTile(policeStationGreenCell1);
		policeStationGreenTiles[3] = new StaticTiledMapTile(policeStationGreenCell2);
		
		fireStationRedactor = loadTexture("data/fireStation_redactor.png");
		fireStationRedactorRegion = new TextureRegion(fireStationRedactor);
		fireStation = loadTexture("data/fireStation.png");
		fireStationCell1 = new TextureRegion(fireStation, 0, 0, 64, 96);
		fireStationCell2 = new TextureRegion(fireStation, 64, 0, 64, 96);
		fireStationCell3 = new TextureRegion(fireStation, 0, 96, 64, 96);
		fireStationCell4 = new TextureRegion(fireStation, 64, 96, 64, 96);
		fireStationSelected = loadTexture("data/fireStationSelected.png");
		selectedFireStationCell1 = new TextureRegion(fireStationSelected, 0, 0, 64, 96);
		selectedFireStationCell2 = new TextureRegion(fireStationSelected, 64, 0, 64, 96);
		selectedFireStationCell3 = new TextureRegion(fireStationSelected, 0, 96, 64, 96);
		selectedFireStationCell4 = new TextureRegion(fireStationSelected, 64, 96, 64, 96);
		fireStationGreen = loadTexture("data/fireStationGreen.png");
		fireStationGreenCell1 = new TextureRegion(fireStationGreen, 0, 0, 64, 96);
		fireStationGreenCell2 = new TextureRegion(fireStationGreen, 64, 0, 64, 96);
		fireStationGreenCell3 = new TextureRegion(fireStationGreen, 0, 96, 64, 96);
		fireStationGreenCell4 = new TextureRegion(fireStationGreen, 64, 96, 64, 96);
		fireStationTiles = new StaticTiledMapTile[4];
		fireStationTiles[0] = new StaticTiledMapTile(Assets.fireStationGreenCell3);
		fireStationTiles[1] = new StaticTiledMapTile(Assets.fireStationGreenCell4);
		fireStationTiles[2] = new StaticTiledMapTile(Assets.fireStationGreenCell1);
		fireStationTiles[3] = new StaticTiledMapTile(Assets.fireStationGreenCell2);

		hospital= loadTexture("data/hospital.png");
		hospitalCell1 = new TextureRegion(hospital, 0, 0, 64, 96);
		hospitalCell2 = new TextureRegion(hospital, 64, 0, 64, 96);
		hospitalCell3 = new TextureRegion(hospital, 0, 96, 64, 96);
		hospitalCell4 = new TextureRegion(hospital, 64, 96, 64, 96);
		hospitalCell5 = new TextureRegion(hospital, 0, 192, 64, 96);
		hospitalCell6 = new TextureRegion(hospital, 64, 192, 64, 96);
		hospitalSelected = loadTexture("data/hospitalSelected.png");
		hospitalSelectedCell1 = new TextureRegion(hospital, 0, 0, 64, 96);
		hospitalSelectedCell2 = new TextureRegion(hospital, 64, 0, 64, 96);
		hospitalSelectedCell3 = new TextureRegion(hospital, 0, 96, 64, 96);
		hospitalSelectedCell4 = new TextureRegion(hospital, 64, 96, 64, 96);
		hospitalSelectedCell5 = new TextureRegion(hospital, 0, 192, 64, 96);
		hospitalSelectedCell6 = new TextureRegion(hospital, 64, 192, 64, 96);
		hospitalGreen = loadTexture("data/hospitalGreen.png");
		hospitalGreenCell1 = new TextureRegion(hospitalGreen, 0, 0, 64, 96);
		hospitalGreenCell2 = new TextureRegion(hospitalGreen, 64, 0, 64, 96);
		hospitalGreenCell3 = new TextureRegion(hospitalGreen, 0, 96, 64, 96);
		hospitalGreenCell4 = new TextureRegion(hospitalGreen, 64, 96, 64, 96);
		hospitalGreenCell5 = new TextureRegion(hospitalGreen, 0, 192, 64, 96);
		hospitalGreenCell6 = new TextureRegion(hospitalGreen, 64, 192, 64, 96);
		hospitalRedactor = loadTexture("data/hospitalRedactor.png");
		hospitalRedactorRegion = new TextureRegion(hospitalRedactor);
		hospitalGreenTiles = new StaticTiledMapTile[6];
		hospitalGreenTiles[0] = new StaticTiledMapTile(Assets.hospitalGreenCell5);
		hospitalGreenTiles[1] = new StaticTiledMapTile(Assets.hospitalGreenCell6);
		hospitalGreenTiles[2] = new StaticTiledMapTile(Assets.hospitalGreenCell3);
		hospitalGreenTiles[3] = new StaticTiledMapTile(Assets.hospitalGreenCell4);
		hospitalGreenTiles[4] = new StaticTiledMapTile(Assets.hospitalGreenCell1);
		hospitalGreenTiles[5] = new StaticTiledMapTile(Assets.hospitalGreenCell2);
		// park
		park = loadTexture("data/park.png");
		parkCell1 = new TextureRegion(park, 0, 0, 64, 64);
		parkCell2 = new TextureRegion(park, 64, 0, 64, 64);
		parkCell3 = new TextureRegion(park, 128, 0, 64, 64);
		parkCell4 = new TextureRegion(park, 0, 64, 64, 64);
		parkCell5 = new TextureRegion(park, 64, 64, 64, 64);
		parkCell6 = new TextureRegion(park, 128, 64, 64, 64);
		parkCell7 = new TextureRegion(park, 0, 128, 64, 64);
		parkCell8 = new TextureRegion(park, 64, 128, 64, 64);
		parkCell9 = new TextureRegion(park, 128, 128, 64, 64);
		parkSelected = loadTexture("data/parkSelected.png");
		parkSelectedCell1 = new TextureRegion(parkSelected, 0, 0, 64, 64);
		parkSelectedCell2 = new TextureRegion(parkSelected, 64, 0, 64, 64);
		parkSelectedCell3 = new TextureRegion(parkSelected, 128, 0, 64, 64);
		parkSelectedCell4 = new TextureRegion(parkSelected, 0, 64, 64, 64);
		parkSelectedCell5 = new TextureRegion(parkSelected, 64, 64, 64, 64);
		parkSelectedCell6 = new TextureRegion(parkSelected, 128, 64, 64, 64);
		parkSelectedCell7 = new TextureRegion(parkSelected, 0, 128, 64, 64);
		parkSelectedCell8 = new TextureRegion(parkSelected, 64, 128, 64, 64);
		parkSelectedCell9 = new TextureRegion(parkSelected, 128, 128, 64, 64);
		parkGreen = loadTexture("data/parkGreen.png");
		parkGreenCell1 = new TextureRegion(parkGreen, 0, 0, 64, 64);
		parkGreenCell2 = new TextureRegion(parkGreen, 64, 0, 64, 64);
		parkGreenCell3 = new TextureRegion(parkGreen, 128, 0, 64, 64);
		parkGreenCell4 = new TextureRegion(parkGreen, 0, 64, 64, 64);
		parkGreenCell5 = new TextureRegion(parkGreen, 64, 64, 64, 64);
		parkGreenCell6 = new TextureRegion(parkGreen, 128, 64, 64, 64);
		parkGreenCell7 = new TextureRegion(parkGreen, 0, 128, 64, 64);
		parkGreenCell8 = new TextureRegion(parkGreen, 64, 128, 64, 64);
		parkGreenCell9 = new TextureRegion(parkGreen, 128, 128, 64, 64);
		parkRedactor = loadTexture("data/parkRedactor.png");
		parkRedactorRegion = new TextureRegion(parkRedactor);
		parkGreenTiles = new StaticTiledMapTile[9];
		parkGreenTiles[0] = new StaticTiledMapTile(Assets.parkGreenCell7);
		parkGreenTiles[1] = new StaticTiledMapTile(Assets.parkGreenCell8);
		parkGreenTiles[2] = new StaticTiledMapTile(Assets.parkGreenCell9);
		parkGreenTiles[3] = new StaticTiledMapTile(Assets.parkGreenCell4);
		parkGreenTiles[4] = new StaticTiledMapTile(Assets.parkGreenCell5);
		parkGreenTiles[5] = new StaticTiledMapTile(Assets.parkGreenCell6);
		parkGreenTiles[6] = new StaticTiledMapTile(Assets.parkGreenCell1);
		parkGreenTiles[7] = new StaticTiledMapTile(Assets.parkGreenCell2);
		parkGreenTiles[8] = new StaticTiledMapTile(Assets.parkGreenCell3);
		//  Wtc
		wtc = loadTexture("data/worldTradeCenter.png");
		wtcCell1 = new TextureRegion(wtc, 0, 0, 64, 213);
		wtcCell2 = new TextureRegion(wtc, 64, 0, 64, 213);
		wtcCell3 = new TextureRegion(wtc, 0, 213, 64, 213);
		wtcCell4 = new TextureRegion(wtc, 64, 213, 64, 213);
		wtcSelected = loadTexture("data/worldTradeCenterSelected.png");
		wtcSelectedCell1 = new TextureRegion(wtcSelected, 0, 0, 64, 213);
		wtcSelectedCell2 = new TextureRegion(wtcSelected, 64, 0, 64, 213);
		wtcSelectedCell3 = new TextureRegion(wtcSelected, 0, 213, 64, 213);
		wtcSelectedCell4 = new TextureRegion(wtcSelected, 64, 213, 64, 213);
		wtcGreen = loadTexture("data/worldTradeCenterGreen.png");
		wtcGreenCell1 = new TextureRegion(wtcGreen, 0, 0, 64, 213);
		wtcGreenCell2 = new TextureRegion(wtcGreen, 64, 0, 64, 213);
		wtcGreenCell3 = new TextureRegion(wtcGreen, 0, 213, 64, 213);
		wtcGreenCell4 = new TextureRegion(wtcGreen, 64, 213, 64, 213);
		wtcRedactor = loadTexture("data/worldTradeCenterRedactor.png");
		wtcGreenTiles = new StaticTiledMapTile[4];
		wtcGreenTiles[0] = new StaticTiledMapTile(Assets.wtcGreenCell3);
		wtcGreenTiles[1] = new StaticTiledMapTile(Assets.wtcGreenCell4);
		wtcGreenTiles[2] = new StaticTiledMapTile(Assets.wtcGreenCell1);
		wtcGreenTiles[3] = new StaticTiledMapTile(Assets.wtcGreenCell2);
		
	}

	
}
